 development:
    adapter: postgresql
    database: hiremonterey_development
    username: postgres
    password: Bosco1
    host: localhost
    encoding: UTF8

test:
    adapter: postgresql
    database: hiremonterey_test
    username: postgres
    password: Bosco1
    host: localhost
    encoding: UTF8

production:
    adapter: postgresql
    database: hiremonterey_production
    username: postgres
    password: Bosco1
    host: localhost
    encoding: UTF8
